### PR TITLE
fix(sem): noreturn analysis for `void` exprs

### LINKED ISSUE #1453: false positive in nested noreturn algorithm
### Example

```nim
let x =
  if true:
    1
  else:
    if true:
      echo "fun"
    else:
      raise newException(Defect, "gone")
```

### Actual Output

Complies successfully

### Expected Output

Should not compile at all

### Possible Solution

This should be changed to verify that either it has a type (a real expression), or all branches must ends with noreturn.

https://github.com/nim-works/nimskull/blob/677964ce59a40112b7d21000db65c5a6f8dd8ffe/compiler/ast/ast_query.nim#L703-L704

### PR DESCRIPTION
**Pull request by saem**
## Summary

`void`  branches preceeding with no-return terminal branches are checked
with no-return analysis to avoid false positives.

## Details

The analysis is updated to recursively check  `if/elif/of/except` 
non-terminal branches as well as the terminal branch.

Fixes https://github.com/nim-works/nimskull/issues/1453

### CODE REVIEW

**Comment by zerbina** [comment]
Ah, dang -- I thought about this case when reviewing the previous PR, but somehow convinced myself it isn't a problem.

I do think it makes sense to fully use recursion now -- in my opinion, it's easier to reason about:
```nim
proc endsInNoReturn*(n: PNode): bool =
  ## Checks if expression `n` ends in an unstructured exit (raise, return,
  ## etc.) or a call of a noreturn proc. This is meant to be called on a
  ## semmed `n`.
  case n.kind
  of nkStmtList, nkStmtListExpr:
    result = n.len > 0 and endsInNoReturn(n[^1])
  of nkBlockStmt, nkExceptBranch, nkElifBranch, nkElse, nkOfBranch:
    result = endsInNoReturn(n[^1])
  of nkIfStmt:
    for it in n.items:
      result = endsInNoReturn(it[^1])
      if not result:
        break
  of nkCaseStmt:
    # skip the selector expression
    for i in 1..<n.len:
      result = endsInNoReturn(n[i])
      if not result:
        break
  of nkTryStmt:
    # ignore the 'finally' -- it doesn't contribute to the type
    for i in 0..<(n.len - ord(n[^1].kind == nkFinally)):
      result = endsInNoReturn(n[i])
      if not result:
        break
  of nkLastBlockStmts:
    result = true
  of nkCallKinds:
    result = n[0].kind == nkSym and sfNoReturn in n[0].sym.flags
  else:
    result = false
```
(this code also fixes the `tnoreturn_nested.nim` test failure.)

**Comment by saem** [comment]
> Ah, dang -- I thought about this case when reviewing the previous PR, but somehow convinced myself it isn't a problem.

You're not the only one. 😆 

> I do think it makes sense to fully use recursion now -- in my opinion, it's easier to reason about:
> 
> ```nim
> proc endsInNoReturn*(n: PNode): bool =
>   ## Checks if expression `n` ends in an unstructured exit (raise, return,
>   ## etc.) or a call of a noreturn proc. This is meant to be called on a
>   ## semmed `n`.
>   case n.kind
>   of nkStmtList, nkStmtListExpr:
>     result = n.len > 0 and endsInNoReturn(n[^1])
>   of nkBlockStmt, nkExceptBranch, nkElifBranch, nkElse, nkOfBranch:
>     result = endsInNoReturn(n[^1])
>   of nkIfStmt:
>     for it in n.items:
>       result = endsInNoReturn(it[^1])
>       if not result:
>         break
>   of nkCaseStmt:
>     # skip the selector expression
>     for i in 1..<n.len:
>       result = endsInNoReturn(n[i])
>       if not result:
>         break
>   of nkTryStmt:
>     # ignore the 'finally' -- it doesn't contribute to the type
>     for i in 0..<(n.len - ord(n[^1].kind == nkFinally)):
>       result = endsInNoReturn(n[i])
>       if not result:
>         break
>   of nkLastBlockStmts:
>     result = true
>   of nkCallKinds:
>     result = n[0].kind == nkSym and sfNoReturn in n[0].sym.flags
>   else:
>     result = false
> ```
> 
> (this code also fixes the `tnoreturn_nested.nim` test failure.)

Yeah, I didn't want to go that route, but I don't think anything else will be pleasant to read.

File: compiler/ast/ast_query.nim [hunk 1]
```diff
@@ -694,27 +694,34 @@ proc endsInNoReturn*(n: PNode): bool =
...
+  case n.kind
+  of nkStmtList, nkStmtListExpr:
+    result = n.len > 0 and endsInNoReturn(n[^1])
+  of nkBlockStmt, nkExceptBranch, nkElifBranch, nkElse, nkOfBranch:
+    result = endsInNoReturn(n[^1])
+  of nkIfStmt:
+    for it in n.items:
+      result = endsInNoReturn(it[^1])
+      if not result:
+        break
```
Comment (zerbina) [inline compiler/ast/ast_query.nim:706]:
```suggestion
        break
    # only noreturn if the 'if' is exhaustive
    result = result and n[^1].kind == nkElse
```

File: compiler/ast/ast_query.nim [hunk 2]
```diff
@@ -694,27 +694,34 @@ proc endsInNoReturn*(n: PNode): bool =
...
+  of nkCaseStmt:
+    # skip the selector expression
+    for i in 1..<n.len:
+      result = endsInNoReturn(n[i])
+      if not result:
+        break
```
Comment (zerbina) [inline compiler/ast/ast_query.nim:713]:
```suggestion
        break
    # only noreturn if the 'case' is exhaustive
    result = result and n[^1].kind == nkElse
```

**Review by zerbina — COMMENTED** [review]
Ugh, the handling for non-exhaustive `if`/`case` statements is still missing.
```nim
if true:
  1
else:
  if true:   # <- `endsInNoReturn` would return true
    return
```

If added two suggestions for the fix. You might also want to add an additional test.

**Comment by zerbina** [comment]
@saem: Sorry for aborting the merge, but I just noticed another issue that's probably better fixed as part of this PR.

**Comment by saem** [comment]
> @saem: Sorry for aborting the merge, but I just noticed another issue that's probably better fixed as part of this PR.

No problem, I'll add some more tests. I haven't been able to think about the testing for this change all that well, so I'll take a day or two with it.

File: compiler/ast/ast_query.nim (hunk 2 above)
Comment (saem) [reply compiler/ast/ast_query.nim:713]: Is this true, because if it's an enum and you list all possible values, then an `else` isn't required, i.e.:

```nim
var x: bool
case x
of true: discard
of false: discard
```

Comment (zerbina) [reply compiler/ast/ast_query.nim:713]: You're right, those would lead to false negatives. An updated suggestion:
```suggestion
        break
    if result:
      result = n[0].typ.skipTypes(abstractRange).kind notin {tyString, tyFloat..tyFloat64} or
               n[^1].kind == nkElse
```
As per `semCase`, only `string` and `float` values can be non-exhaustive while omitting the `else` branch.

Comment (saem) [reply compiler/ast/ast_query.nim:713]: I'll see, but I suspect I'm going to have to use/introduce a node flag to pass the information along.

Comment (saem) [reply compiler/ast/ast_query.nim:713]: > You're right, those would lead to false negatives. An updated suggestion:
> 
> As per `semCase`, only `string` and `float` values can be non-exhaustive while omitting the `else` branch.

D'oh, I saw this after my change, this is simpler as I can rely on the initial exhaustiveness check instead of redoing the whole thing. I'll update my latest change with a simplified version.

**Comment by saem** [comment]
I expect the tests to pass, and we could consider this PR done, although see the caveat below.

---

Thinking about it more an area where this might not work is something nested inside a loop:

```nim
proc foo() =
  let x =
  while true:
    return
```

The chance of writing that code is very small, and thankfully it's only a false-negative, but it looks like I need to expand the traversal to include `while` and `for` loop bodies. If I'm being really pedantic, then I should also check for `while (return; true): ...`, but that applies to all predicate positions.

File: compiler/ast/ast_query.nim [hunk 3]
```diff
@@ -694,27 +694,44 @@ proc endsInNoReturn*(n: PNode): bool =
...
+    let
+      caseType = n[0].typ.skipTypes(abstractRange)
+      requiresElse =
+        case caseType.kind
+        of tyFloat..tyFloat64, tyString:
+          true
+        else:
+          false
```
Comment (zerbina) [inline compiler/ast/ast_query.nim]:
```suggestion
      requiresElse = caseType.kind in {tyFloat..tyFloat64, tyString}
```
A soft suggestion. I don't think the `case` helps readability.

I'd have also suggested inlining `caseType`, but that would have made the line longer than 80 characters, so I let it be.

Comment (saem) [reply compiler/ast/ast_query.nim]: I dropped `caseType` and made it one expression, I much prefer the expression form, thanks.

**Review by zerbina — APPROVED** [review]
Looks good to me.

> The chance of writing that code is very small, and thankfully it's only a false-negative, but it looks like I need to expand the traversal to include while and for loop bodies

Given that neither `while` nor `for` can be used as expressions at the moment (outside of `typeof` expressions, but those are super special anyway), I don't think this is something to worry about.

It'd become relevant once introducing a `unit` type and making `while` and `for` real expressions, but at that point `endsInNoReturn` would be obsolete anyway.
