### PR TITLE
fix(sem): crash with manual `=destroy` hook call

### LINKED ISSUE #1161: compiler crash with attempt to redefine destructor
### Specification

I managed to instantiate an object before defining a destructor for it, which caused the compiler to crash.

### Example
```nim
type Grenade = object
var g: Grenade
proc `=destroy`(g: var Grenade) = discard
```

### Actual Output
Compiler crash.

```
Traceback (most recent call last)
/home/adavidoff/git/nimskull/compiler/nim.nim(154) nim
/home/adavidoff/git/nimskull/compiler/nim.nim(89) handleCmdLine
/home/adavidoff/git/nimskull/compiler/front/main.nim(539) mainCommand
/home/adavidoff/git/nimskull/compiler/front/main.nim(491) compileToBackend
/home/adavidoff/git/nimskull/compiler/front/main.nim(214) commandCompileToC
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(212) compileProject
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(128) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(284) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(950) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(868) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3364) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1441) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3854) semExpr
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(405) evalImport
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(362) impMod
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(319) myImportModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(161) importModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(128) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(284) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(950) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(868) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3364) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1441) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3843) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2993) semRoutineDef
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2167) semProcAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(571) semAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(562) tryMacroPragma
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1190) afterCallActions
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(788) semMacroExpr
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(728) semAfterMacroCall
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3843) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2993) semRoutineDef
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2167) semProcAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(571) semAnnotation
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(562) tryMacroPragma
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1190) afterCallActions
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(788) semMacroExpr
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(728) semAfterMacroCall
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3664) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1413) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1150) semOverloadedCallAnalyseEffects
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(573) semOverloadedCall
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(326) resolveOverloads
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(73) pickBestCandidate
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3155) matches
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3055) matchesAux
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(2614) prepareOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(49) semOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3664) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1417) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1190) afterCallActions
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(788) semMacroExpr
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(728) semAfterMacroCall
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3843) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3025) semRoutineDef
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2776) semProc
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2712) semProcAux
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(2348) semProcBody
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3821) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3260) semStmtList
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3830) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(84) semWhile
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3364) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1441) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3821) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3260) semStmtList
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3831) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(235) semTry
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(103) semExprBranchScope
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(95) semExprBranch
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3821) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3260) semStmtList
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3689) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(2916) semMagic
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1413) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1150) semOverloadedCallAnalyseEffects
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(573) semOverloadedCall
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(326) resolveOverloads
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(73) pickBestCandidate
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3155) matches
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(3055) matchesAux
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(2614) prepareOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(49) semOperand
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3689) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(2916) semMagic
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1413) semDirectOp
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1150) semOverloadedCallAnalyseEffects
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(573) semOverloadedCall
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(326) resolveOverloads
/home/adavidoff/git/nimskull/compiler/sem/semcall.nim(56) pickBestCandidate
/home/adavidoff/git/nimskull/compiler/sem/sigmatch.nim(158) initCallCandidate
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
Error: cannot bind another '=destroy' to: Grenade
```
### Possible Solution

Don't dereference nil.

### Additional Information
My workaround looks like this:
```nim
proc initCallCandidate*(ctx: PContext, c: var TCandidate, callee: PSym,
                        calleeScope = -1) =
  initCandidate(ctx, c, callee.typ)
  c.calleeSym = callee
  if callee.kind in skProcKinds and calleeScope == -1:
    if callee.originatingModule == ctx.module:
      c.calleeScope = 2
      var owner = callee
      while true:  # line 156 in compiler/sem/sigmatch.nim      
        # owner becomes nil...
        owner = owner.skipGenericOwner                                            
        if owner.isNil:                                                           
          # i reset it here to work around the bug                                      
          owner = callee                                                                
          break                                                                         
        else:                                                                           
          if owner.kind == skModule: break                                              
          inc c.calleeScope
```

### PR DESCRIPTION
**Pull request by zerbina**
## Summary

Fix a bug where manually calling the `=destroy` (or `=trace`) hook for
a type where the hook is compiler-generated crashed the compiler when
the call is within a typed procedure definition that is returned by a
macro or template.

Fixes https://github.com/nim-works/nimskull/issues/1161.

## Details

All compiler-synthesized hook procedures are marked as `sfFromGeneric`.
The `owner` of such procedures is expected to be the generic procedure
the procedure is an instantiation of (`skipGenericOwner` the immediate
owner), but this wasn't the case for the synthesized hooks, where the
owner was set to the owner of the type the hook is synthesized for.

When a compiler-synthesized hook is used in overload resolution, the
search for the owning module in `initCallCandidate` skips over the
`skModule` symbol (via `skipGenericOwner`), thus resulting in an NPE.

To fix the issue, the owner of synthesized hook procedures is now set
to the hook kind's corresponding generic magic procedure from the
`system` module, making the produced symbols well-formed.

### CODE REVIEW

File: tests/lang_callable/macros/tsynthesized_destroy_hook_roundtrip.nim [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+  proc f() =
+    # the bug only surfaced when the hook call is part of a procedure. Types
+    # that need a compiler-synthesized as well as those that don't were
+    # affected.
+    var v = NoHookObject()
+    `=destroy`(v)
+    var v2 = HookObject()
+    `=destroy`(v2)
+
+# the same bug happend when using a template:
```
Comment (saem) [inline tests/lang_callable/macros/tsynthesized_destroy_hook_roundtrip.nim]:
```suggestion
# the same bug happened when using a template:
```

Minor typo

**Review by saem — APPROVED** [review]
Looks good to me, very minor typo, not a blocker.
