### PR TITLE
debug: refactor debugutils tracer templates

### LINKED ISSUE #194: sem trace segfaults when executed without `--stacktrace` enabled (ex: `-d:release`, `-d:danger`).
The current implementation assumes that stacktrace exists, but this is not the case for release/danger builds, and those sometimes need to be debugged as well. This is a follow-up todo for the https://github.com/nim-works/nimskull/pull/191 - it adds another debug utils step kind, the template implementation needs to be refactored into a more manageable structure where check can be added in a single place, right now it is impossible to do cleanly.

### PR DESCRIPTION
**Pull request by haxscramper**
- REFACTOR implementation of the debug tracer templates from `debugutils`.
  Add generalized template that allows modifiying remaining bits that are
  needed to produce full debug step information.
- FIX debug trace segfault/out-of-bounds error for `--stacktrace=off`. This
  commit closes https://github.com/nim-works/nimskull/issues/194

### CODE REVIEW

File: compiler/utils/debugutils.nim [hunk 1]
```diff
@@ -140,36 +140,108 @@ template addInNimDebugUtilsAux(conf: ConfigRef; prcname: string;
...
+
+const instDepth = -5
+template traceEnterIt*(
+    params: StepParams,
+    body: untyped,
+    templateDepth: int = instDepth
+  ): untyped =
+  ## Convenience wrapper around the `traceStepImpl`. If called from user
+  ## code `templateDepth` parameter must be specified as well - it controls
+  ## depth of the template instantiatoin location that is need to be
```
Comment (saem) [inline compiler/utils/debugutils.nim]:
```suggestion
  ## depth of the template instantiation location that is need to be
```

File: compiler/utils/debugutils.nim [hunk 2]
```diff
@@ -140,36 +140,108 @@ template addInNimDebugUtilsAux(conf: ConfigRef; prcname: string;
...
+  ## accounted for. With current implementation of the debugutils this
+  ## value is set to `-5` (`instDepth` default), for you code it might be
```
Comment (saem) [inline compiler/utils/debugutils.nim]:
```suggestion
  ## value is set to `-5` (`instDepth` default), for your code it might be
```

**Review by saem — CHANGES_REQUESTED** [review]
Just a couple typos, it's change and fewer crashes

**Review by saem — APPROVED** [review]
LGTM 🥳
