### PR TITLE
Produce a meaningful error message for invalid module name

### LINKED ISSUE #720: Crash when compiling a-b.nim
The compiler crashes with trying to compile a file with `-` in it.

```
❯ touch sol-nimskull.nim

❯ nimskull c sol-nimskull.nim
.......................................................
Error: invalid module name: '<nil tree>' [rsemInvalidModuleName]
modules.nim(114, 16) compiler msg instantiated here [MsgOrigin]
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp $1 <file>'
```

### PR DESCRIPTION
**Pull request by alaviss**
## Summary
While the AST form of the error generated by  `modules/modulepaths`  is
handled in  `cli_reporter` , the symbol form was not, creating terrible
error messages such as:

    Error: invalid module name '<nil tree>'

This PR makes cli_reporter aware of the symbol form generated by 
`modules/modules` , fixing the bad error message.

## Details
*  `cli_reporter`  now handles the symbol form of 
`rsemInvalidModuleName`  correctly.
*  `modules/modules`  now raises  `rsemInvalidModuleName`  with line
information, allowing user and tools to know which file the error
originated from.

Fixes https://github.com/nim-works/nimskull/issues/720

### CODE REVIEW

File: tests/errmsgs/tinvalid-name.nim [hunk 1]
```diff
@@ -0,0 +1,4 @@
+discard """
+  description: Test that a proper error message is printed for a module with invalid name
```
Comment (zerbina) [inline tests/errmsgs/tinvalid-name.nim]:
```suggestion
  description: '''
    Test that a proper error message is printed for a module with invalid name
  '''
```
Nit-pick: line length.

**Review by zerbina — APPROVED** [review]
Looks good to me, thank you for reviving the fix!

I think the current description is okay as is, but for future PRs, especially those with a more outside-facing change (like this fix), could you focus the summary more on the user-facing changes? Along the lines of "this was the visible previous behaviour, this is how it behaves now", with the implementation details going into the "Details" section.
