### PR TITLE
fix(sem): wrong error reported for `raise`

### LINKED ISSUE #112: raise might eat errors when used with strformat
### Example

```nim
import std/strformat

proc exec(cmd: string, args: varargs[string]) =
  let x = @[cmd] & args
  raise newException(CatchableError):
    fmt"{x}"
  # Only referring to a "broken" variable would this issue happen
```

### Actual Output

```
test.nim(5, 3) Error: only a 'ref object' can be raised
```

### Expected Output

The real cause of the error (invalid expression for `x`) should show up instead

```
test.nim(4, 18) Error: type mismatch: got <seq[string], varargs[string]>
but expected one of:
proc `&`[T](x, y: seq[T]): seq[T]
  first type mismatch at position: 2
  required type for y: seq[T]
  but expression 'args' is of type: varargs[string]
proc `&`[T](x: T; y: seq[T]): seq[T]
  first type mismatch at position: 2
  required type for y: seq[T]
  but expression 'args' is of type: varargs[string]
proc `&`[T](x: seq[T]; y: T): seq[T]
  first type mismatch at position: 2
  required type for y: T
  but expression 'args' is of type: varargs[string]
5 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: @[cmd] & args
```

### Additional information

* Mainline does not have this issue

### PR DESCRIPTION
**Pull request by zerbina**
## Summary

Fix errors in expressions within `raise` statements being hidden
behind an "only a 'ref object' can be raised" error.

Fixes https://github.com/nim-works/nimskull/issues/112 

## Details

* make `semRaise` `nkError`-aware (proper error propagation)
* don't modify input AST in `semRaise`
* replace `localReport` in `semRaise` with `nkError`; the necessary
  diagnostics corresponding to the legacy reports are introduced

### CODE REVIEW

File: compiler/sem/semstmts.nim [hunk 1]
```diff
@@ -1730,20 +1730,26 @@ proc semCase(c: PContext, n: PNode; flags: TExprFlags): PNode =
...
+  else:
+    result[0] = semExprWithType(c, n[0])
+    let typ = result[0].typ
+    if result[0].kind == nkError:
+      result = c.config.wrapError(result)
+    elif not isImportedException(typ, c.config):
+      let refTyp = typ.skipTypes({tyAlias, tyGenericInst})
+      if refTyp.kind != tyRef:
+        result = c.config.newError(result,
+          PAstDiag(kind: adSemCannotBeRaised, excType: typ))
```
Comment (saem) [inline compiler/sem/semstmts.nim]: Did you already consider making `excType` a query, basically fetching it from `wrongNode`?

**Review by saem — APPROVED** [review]
New behavior itself is all good. One minor consideration of using a query instead of saving state for the exception type, but that's about it.

File: compiler/sem/semstmts.nim (hunk 1 above)
Comment (zerbina) [reply compiler/sem/semstmts.nim]: No, I had forgotten about the move to a more query-focused diagnostic-to-report tranlsation. Thank you for the reminder -- I'll change it.
