### PR TITLE
mir2cg: handle unary int and float plus

### LINKED ISSUE #1681: unreachable unary plus crashes the compiler
### Specification

Unreachable unary plus crashes the compiler.

### Example

```nim
var w = 1
discard +w
```

### Actual Output
```
/home/adavidoff/git/nimskull/compiler/nim.nim(151) nim
/home/adavidoff/git/nimskull/compiler/nim.nim(88) handleCmdLine
/home/adavidoff/git/nimskull/compiler/front/main.nim(522) mainCommand
/home/adavidoff/git/nimskull/compiler/front/main.nim(477) compileToBackend
/home/adavidoff/git/nimskull/compiler/front/main.nim(207) commandCompileToC
/home/adavidoff/git/nimskull/compiler/backend/cbackend.nim(93) generateCode
/home/adavidoff/git/nimskull/compiler/backend/cgbackend.nim(259) generateCode
/home/adavidoff/git/nimskull/compiler/backend/cgbackend.nim(186) processEvent
/home/adavidoff/git/nimskull/compiler/backend/cgbackend.nim(137) addProc
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(3315) defineProc
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(3284) procToCgir
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(3027) toTree
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(2924) toTreeStmts
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(3027) toTree
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(2924) toTreeStmts
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(3031) toTree
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(2749) stmtToCgir
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(2291) exprToCgir
/home/adavidoff/git/nimskull/compiler/backend/mir2cg.nim(2099) magicToCgir
/home/adavidoff/git/nimskull/lib/system/assertions.nim(129) unreachableImpl
/home/adavidoff/git/nimskull/lib/system/assertions.nim(124) unreachableImpl
/home/adavidoff/git/nimskull/lib/system/assertions.nim(25) raiseAssert
/home/adavidoff/git/nimskull/lib/system/fatal.nim(50) sysFatal
Error: unhandled exception: mir2cg.nim(2099, 16) unreachable: mUnaryPlusI [AssertionDefect]
```

### Expected Output

No.

### Additional Information
```
Nimskull Compiler Version 0.1.0-dev.21571 [linux: amd64]

Source hash: 7898cfcb12cd97fe7cd6c0ccfeb0d35cb6dd8c75
Source date: 2026-01-18

active boot switches: -d:release⏎
```

### PR DESCRIPTION
**Pull request by saem**
## Summary

Unary int and float plus operations no longer result in a compiler
crash, and are handled correctly as a no-op.

## Details

`mir2cg`  now correctly handles no-oping unary int and float plus
operations, where previously it didn't and fell through to the catch-all
assertion resulting in a compiler crash. Also added a test to avoid
future regressions.

fixes: https://github.com/nim-works/nimskull/issues/1681

### CODE REVIEW

**Review by alaviss — APPROVED** [review]

File: tests/ccgbugs/tunary_plus.nim [hunk 1]
```diff
@@ -0,0 +1,38 @@
+discard """
+  description: "Compiler regression tests for unary plus"
```
Comment (zerbina) [inline tests/ccgbugs/tunary_plus.nim]: I think it'd be better to have this test be located in `tests/magics` and to remove the regression test framing, making it just a test for the unary plus operator.

File: tests/magics/tunary_plus.nim [hunk 2]
```diff
@@ -0,0 +1,38 @@
+discard """
+  description: "Compiler regression tests for unary plus"
+"""
```
Comment (zerbina) [inline tests/magics/tunary_plus.nim:4]:
```suggestion
  targets: "c js vm"
"""
```

**Review by zerbina — COMMENTED** [review]
The `mir2cg` change looks good, but I think the test should be moved.

For the PR summary, could you change it such that it's clear(er) that the PR/commit is a bugfix and what its impact is (i.e., using an unary plus operator no longer crashes the compiler)?

File: tests/ccgbugs/tunary_plus.nim (hunk 1 above)
Comment (saem) [reply tests/ccgbugs/tunary_plus.nim]: Moved and reworded.

Also added a static float addition, just to make it symmetric

File: tests/magics/tunary_plus.nim (hunk 2 above)
Comment (saem) [reply tests/magics/tunary_plus.nim:4]: Added the targets

**Review by zerbina — APPROVED** [review]
