### PR TITLE
sem: fix invalid case object discriminant crash

### LINKED ISSUE #1680: nested case object with out-of-order discriminator
### Specification

Nested case objects are supported, but out-of-order discriminator definition causes a crash.  If nested case objects aren't supported, perhaps the compiler should merely issue an error instead of crashing outright.

### Example
```nim
type                                                                                         
  AstNode*[T] = object                                                                       
    v*: T
    kids*: int32
    directKids*: int16
    case isLiteral*: bool                                                                    
    of true:                                                                                 
      case litKind*: LiteralKind                                                             
      of lkInt:    n*: int64                                                                 
      of lkFloat:  f*: float64                                                               
      of lkString: s*: uint32
    of false:                                                                                
      discard                                                                                
                                                                                             
  LiteralKind* = enum                                                                        
    lkInt                                                                                    
    lkFloat                                                                                  
    lkString 
```

### Actual Output
```
/home/adavidoff/git/gread/last/nodes.nim(16, 12) Error: undeclared identifier: 'LiteralKind'
/home/adavidoff/git/nimskull/compiler/nim.nim(151) nim
/home/adavidoff/git/nimskull/compiler/nim.nim(88) handleCmdLine
/home/adavidoff/git/nimskull/compiler/front/main.nim(522) mainCommand
/home/adavidoff/git/nimskull/compiler/front/main.nim(477) compileToBackend
/home/adavidoff/git/nimskull/compiler/front/main.nim(204) commandCompileToC
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(218) compileProject
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(133) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(284) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(997) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(909) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3378) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1437) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3865) semExpr
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(416) evalImport
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(361) impMod
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(318) myImportModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(167) importModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(133) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(279) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(997) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(909) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3378) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1437) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3865) semExpr
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(416) evalImport
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(361) impMod
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(318) myImportModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(167) importModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(133) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(284) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(997) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(909) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3378) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1437) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3865) semExpr
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(416) evalImport
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(361) impMod
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(318) myImportModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(167) importModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(133) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(279) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(997) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(909) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3378) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1437) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3865) semExpr
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(416) evalImport
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(361) impMod
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(318) myImportModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(167) importModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(133) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(279) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(997) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(909) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3378) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1437) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3865) semExpr
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(416) evalImport
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(361) impMod
/home/adavidoff/git/nimskull/compiler/modules/importer.nim(318) myImportModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(167) importModule
/home/adavidoff/git/nimskull/compiler/modules/modules.nim(133) compileModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(275) processModule
/home/adavidoff/git/nimskull/compiler/sem/passes.nim(102) processTopLevelStmt
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(997) myProcess
/home/adavidoff/git/nimskull/compiler/sem/sem.nim(909) semStmtAndGenerateGenerics
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3378) semStmt
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(1437) semExprNoType
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3832) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(3274) semStmtList
/home/adavidoff/git/nimskull/compiler/sem/semexprs.nim(3839) semExpr
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(2092) semTypeSection
/home/adavidoff/git/nimskull/compiler/sem/semstmts.nim(1976) typeSectionRightSidePass
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(2275) semTypeNode
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(1121) semObjectNode
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(1006) semRecordNodeAux
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(1000) semRecordNodeAux
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(924) semRecordCase
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(1006) semRecordNodeAux
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(1000) semRecordNodeAux
/home/adavidoff/git/nimskull/compiler/sem/semtypes.nim(907) semRecordCase
/home/adavidoff/git/nimskull/compiler/ast/types.nim(482) firstOrd
/home/adavidoff/git/nimskull/lib/system/assertions.nim(124) unreachableImpl
/home/adavidoff/git/nimskull/lib/system/assertions.nim(25) raiseAssert
/home/adavidoff/git/nimskull/lib/system/fatal.nim(50) sysFatal
Error: unhandled exception: types.nim(482, 16) unreachable: firstOrd - non-ordinal type given: tyForward [AssertionDefect]
```
### Expected Output
No.

### Compiler Version
```
Nimskull Compiler Version 0.1.0-dev.21571 [linux: amd64]

Source hash: 7898cfcb12cd97fe7cd6c0ccfeb0d35cb6dd8c75
Source date: 2026-01-18

active boot switches:⏎
```

### PR DESCRIPTION
**Pull request by saem**
## Summary

The compiler no longer crashes when an invalid discrimanant type is
provided in a variant type declaration.

## Details

The compiler crashed if error reporting beyond the first error was
enabled, and the discrimanant field was invalid. This is because ordinal
field validation functions, which contain assertions on input type, were
being called on an invalid discrimanant field.

Now the checks are only run if the field is a valid type.

Fixes: https://github.com/nim-works/nimskull/issues/1680

### CODE REVIEW

File: compiler/sem/semtypes.nim [hunk 1]
```diff
@@ -888,38 +888,42 @@ proc semRecordCase(c: PContext, n: PNode, check: var IntSet, pos: var int,
   incl(a[0].sym.flags, sfDiscriminant)
   var covered = toInt128(0)
   var chckCovered = false
+  var doOrdinalChecks = true
```
Comment (zerbina) [inline compiler/sem/semtypes.nim]: What's the reason for not reusing `chckCovered` for the guard?

Should you want to keep `doOrdinalChecks`, it should be set to 'false' when the `tyRange` doesn't have the correct base type. With the code as it is right now, using a `float` range as the discriminant only doesn't trigger an internal compiler error because `getOrdValue` (eventually called by `firstOrd`) silently ignores non-ordinal values, but this is shaky.

**Review by zerbina — COMMENTED** [review]
Not using `return` is the right call.

As for the test, in its current form, it wouldn't have caught the internal compiler error. It should either use `matrix: "--errorMax:3"`, or `cmd: "nim check $options $file"` and inline errors.

Having a test for the case where the discriminant type is some other invalid type (e.g., `string`) would be nice for more coverage, but it's not a requirement, given that tests such as this should - in the future - either be automated, or be made obsolete through the use of static analysis of the compiler (or both)

File: compiler/sem/semtypes.nim (hunk 1 above)
Comment (saem) [reply compiler/sem/semtypes.nim]: I don't recall how, but I somehow talked myself into reusing `chckCovered` even though it handles `tyRange` correctly as you said. I've updated the code accordingly.

**Comment by saem** [comment]
I updated the test to have a matrix check for increased error messages.

**Review by zerbina — APPROVED** [review]
The change looks good, thanks.
