### PR TITLE
fix(sem): analysis considers nested noreturn

### LINKED ISSUE #1440: raise within a nested `if` invalidate the outer if-expression
### Example

```nim
let s = [0]

let x =
  if s[0] == 0:
    0
  else:
    if true:
      raise newException(CatchableError, "error")
    else:
      raise newException(CatchableError, "another error")
```

### Actual Output

```
test.nim(5, 5) Error: expression '0' is of type 'int literal(0)' and has to be used (or discarded)
```

### Expected Output

This should not error, as the alternative branch is a `noreturn`.

### Additional Information

* If the `raise` is not nested in an another `if`, no error will occur

### PR DESCRIPTION
**Pull request by saem**
## Summary
No-return analysis ensures that nested final expressions (
`block/case/if/try` ) are accounted for no-return itself.

## Details
Prior to this change if the last expression within a greater expression
was a no-return expression it would not be deemed as such if it was a 
`block/case/if/try` , instead errors would be raised related to discard
checks or that path not resulting in the correct type.

For example, the following would result in an error where  `0`  must be
used or discarded:
```nim
proc foo() =
  let x =
    if false: 10
    else:
      block:
        return
```

Fixes https://github.com/nim-works/nimskull/issues/1440

### CODE REVIEW

File: compiler/ast/ast_query.nim [hunk 1]
```diff
@@ -690,6 +690,16 @@ iterator genericParamsInMacroCall*(macroSym: PSym, call: PNode): (PSym, PNode) =
     if posInCall < call.len:
       yield (genericParam, call[posInCall])
 
+proc endsInNoReturn*(n: PNode): bool =
+  ## checks if expression `n` ends in an unstructured exit (raise, return,
+  ## etc), calls of noreturn proc, or
```
Comment (saem) [inline compiler/ast/ast_query.nim]:
```suggestion
  ## etc) or calls of noreturn proc. This is meant to be called on an semmed `n`.
```

File: compiler/ast/ast_query.nim [hunk 2]
```diff
@@ -690,6 +690,16 @@ iterator genericParamsInMacroCall*(macroSym: PSym, call: PNode): (PSym, PNode) =
     if posInCall < call.len:
       yield (genericParam, call[posInCall])
 
+proc endsInNoReturn*(n: PNode): bool =
+  ## checks if expression `n` ends in an unstructured exit (raise, return,
+  ## etc) or calls of noreturn proc. This is meant to be called on an semmed `n`.
```
Comment (zerbina) [inline compiler/ast/ast_query.nim]:
```suggestion
  ## Checks if expression `n` ends in an unstructured exit (raise, return,
  ## etc.) or a call of a noreturn proc. This is meant to be called on a
  ## semmed `n`.
```
Fixes a few small issues (`an` instead of `a`, plural for call, etc.).

File: tests/lang_exprs/tnoreturn_nested.nim [hunk 3]
```diff
@@ -0,0 +1,53 @@
+discard """
+  description: "
+    Ensure nested noreturn statements are considererd in noreturn analysis
+  "
```
Comment (zerbina) [inline tests/lang_exprs/tnoreturn_nested.nim]:
```suggestion
  description: """
    Ensure nested noreturn statements are considererd in noreturn analysis
  """
```

File: compiler/ast/ast_query.nim [hunk 4]
```diff
@@ -690,6 +690,16 @@ iterator genericParamsInMacroCall*(macroSym: PSym, call: PNode): (PSym, PNode) =
...
+  var it = n
+  while it.kind in {nkStmtList, nkStmtListExpr} and it.len > 0:
+    it = it.lastSon
+  result = it.kind in nkLastBlockStmts or
+    it.kind in {nkIfStmt, nkIfExpr, nkTryStmt, nkCaseStmt, nkTryStmt, nkBlockExpr} and it.typ.isNil or
```
Comment (zerbina) [inline compiler/ast/ast_query.nim]:
```suggestion
    (it.kind in {nkIfStmt, nkTryStmt, nkCaseStmt, nkBlockStmt} and
     it.typ.isEmptyType()) or
```
`nkIfExpr` and `nkBlockExpr` don't need to be handled here, since they're guaranteed to have a non-`void` type.

Some noreturn compound statements can also have a non-nil `typ` (when assigned the `enforceVoidContext` type), so `isEmptyType` (which returns true for both `typ == nil` and `typ.kind == tyVoid`) has to be used.

File: tests/lang_exprs/tnoreturn_nested.nim [hunk 5]
```diff
@@ -0,0 +1,53 @@
...
+
+  doAssert x is int
+
+block nested_in_case:
+  let x =
+    if true:
+      0
+    else:
+      let s = false
+      case
```
Comment (saem) [inline tests/lang_exprs/tnoreturn_nested.nim]:
```suggestion
      case s
```

File: tests/lang_exprs/tnoreturn_nested.nim [hunk 6]
```diff
@@ -0,0 +1,53 @@
+discard """
+  description: """
+    Ensure nested noreturn statements are considererd in noreturn analysis
+  """
```
Comment (zerbina) [inline tests/lang_exprs/tnoreturn_nested.nim]:
```suggestion
  description: '''
    Ensure nested noreturn statements are considererd in noreturn analysis
  '''
```
My bad, it needs to be triple single-quotes.
