### PR TITLE
fix(sem): AST corruption with type expressions

### LINKED ISSUE #1113: type-checking issue with dereferencing expression within templates
The title is a mouthful but I have no better description

### Example

This one affects only ARC:

```nim
type
  O = object

iterator iter(x, y: O): O = discard

template stuff() =
  for _ in iter((ref O)()[], O()):
    discard

stuff()
```

This one affects both GCs:

```nim
type
  O = object

proc foo(x, y: O) = discard

template stuff() =
  foo((ref O)()[], O())

stuff()
```

### Actual Output

First example:

```
$ nim c --gc:arc test.nim
test.nim(7, 16) Error: type mismatch: got <test.O, test.O>
but expected one of:
iterator iter(x, y: O): O
  first type mismatch at position: 1
  required type for x: O
  but expression 'ref O()[]' is of type:

expression: iter(ref O()[], O())
```

Second example:

```
test.nim(9, 6) Error: type mismatch: got <test.O, test.O>
but expected one of:
proc foo(x, y: O)
  first type mismatch at position: 1
  required type for x: O
  but expression 'ref O()[]' is of type:

expression: foo(ref O()[], O())
```

### Expected Output

This should not error

### Additional Information

* ~~Only occurs with `--gc:arc`~~
* Minimized from https://github.com/nim-works/nimskull/blob/7e7226f1904360c2e14c8f57fc9e0f61e5483d58/lib/pure/streamwrapper.nim#L101-L104
* Does not occur if used outside of templates, or if `{.dirty.}` templates are used.

### PR DESCRIPTION
**Pull request by zerbina**
## Summary

Fix a bug in semantic analysis where an expression like `(ref T)()`
would result in an error when used directly within a deref (`x[]`) or
subscript (`x[...]`) expression that itself appears within a template
or generic routine.

Fixes https://github.com/nim-works/nimskull/issues/1113.

## Detail

`semExpr` does not create a copy of the input AST for type expressions,
meaning that the input AST had its type set and the `nfSem` flag
included, which is both wrong, as input AST must not be mutated in any
way.

### The symptom

The `(ref T)()` AST is processed through `semIndirectOp`, which first
analyses the expression in the callee slot and then dispatches to the
correct procedure (`semObjConstr`, in this case).

When `semObjConstr`, calls `semTypeNode` on the type expression,
`semTypeNode` overrides the node's type with `tyRef[T]` (it was
`tyTypeDesc[tyRef[T]]`).

If the `(ref T)()` expression is analysed again, which happens for
the `mArrGet` magic procedure calls that `x[]` is turned into when
appearing within templates or generic routines, the node is seen as
already analysed (due to the `nfSem` flag), meaning that it was not
typed as `tyTypeDesc` again, causing `semIndirectOp` to treat the
`(ref T)()` expression as a call (which then resulted in an error).

### The fix

`semExpr` now creates a copy of the input AST when analysing type
expressions, via `semTypeNode2`, preventing the `nfSem` flag from being
included on the original AST.

### CODE REVIEW

**Review by saem — APPROVED** [review]
Ah, this is very similar to the `semAfterMacroCall` fix, I suspect there are a few more of these lying around. I'll try to remember to audit some more `semTypeNode` callsites.

File: tests/lang_exprs/ttype_expr_ast_corruption.nim [hunk 1]
```diff
@@ -0,0 +1,20 @@
+discard """
+  description: '''
+    Ensure that a type expression can be used in the type slot of an object
+    construction syntax, which is itself the argument to a `[]` procedure
+    call
+  '''
```
Comment (alaviss) [inline tests/lang_exprs/ttype_expr_ast_corruption.nim:7]: I don't know if it's a standard practice for nimskull to go like this but a link to the original issue would be helpful

**Review by alaviss — APPROVED** [review]
LGTM

File: tests/lang_exprs/ttype_expr_ast_corruption.nim (hunk 1 above)
Comment (saem) [reply tests/lang_exprs/ttype_expr_ast_corruption.nim:7]: hah, we've not had issues so we're used to writing descriptions. 😄
