### PR TITLE
cmdlinehelper: increment errorCounter on config parse error

### LINKED ISSUE #1112: error in nim.cfg does not make the compiler quit with an error code
### Example

Use this `test.nim.cfg` with an empty `test.nim`:

```text
--gibberish
```

### Actual Output

```
$ nim c test.nim || echo got error
test.nim.cfg(1, 3) Error: Invalid command line option - gibberish
```

### Expected Output

```
$ nim c test.nim || echo got error
test.nim.cfg(1, 3) Error: Invalid command line option - gibberish
got error
```

### Possible Solution

* Write error handling code for this case: https://github.com/nim-works/nimskull/blob/7e7226f1904360c2e14c8f57fc9e0f61e5483d58/compiler/nim.nim#L159-L161

### PR DESCRIPTION
**Pull request by alaviss**
## Summary
Previously we did not increment this counter, making configuration
errors yield successful exit code.

## Details
* Added a new "None" diagnostic level to simplify handling code.
* Increments error counter on Error or worse.

Fixes https://github.com/nim-works/nimskull/issues/1112

### CODE REVIEW

File: tests/errmsgs/tconfig_error.nim [hunk 1]
```diff
@@ -0,0 +1,10 @@
+discard """
+  description: '''
+  Test that a config file with invalid option will yield an error with
+  non-zero exit code.
+
+  Ref https://github.com/nim-works/nimskull/issues/1112
```
Comment (zerbina) [inline tests/errmsgs/tconfig_error.nim]:
```suggestion
    Test that a config file with invalid option will yield an error with
    non-zero exit code.

    References https://github.com/nim-works/nimskull/issues/1112
```
Indenting the body makes the relationship easier to parse. I'd also suggest not abbreviating "References" in test specifications (or at least using "Refs").

File: compiler/front/cmdlinehelper.nim [hunk 2]
```diff
@@ -125,18 +126,23 @@ proc writeConfigEvent(conf: ConfigRef,
...
       of cekProgressConfStart, cekProgressPathAdded:
-        styleSeverity configDiagSevInfo # xxx: not really a hint
+        configDiagSevInfo # xxx: not really a hint
       of cekWriteConfig:
-        "" # not a log/diagnostic like the rest; has none
+        configDiagSevNone # not a log/diagnostic like the rest; has none
+
+    severity = styleSeverity diagSeverity
+
+  if diagSeverity <= configDiagSevError:
```
Comment (saem) [inline compiler/front/cmdlinehelper.nim:144]: (no change required) I regret the ordering of the enum, because it'd be so much nicer if this was a `>=`, oh well.

**Review by saem — APPROVED** [review]

**Comment by saem** [comment]
/merge

Thanks!
